# Generated by Django 3.2 on 2023-05-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_backend', '0003_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
